app = "amazing-api"   # Replace with your Fly.io app name

[build]
  builder = "paketobuildpacks/builder:base"  # Use this if you're not using a Dockerfile

[env]
  PORT = "3000"  # Match this to the port your app listens on, if necessary

[[services]]
  internal_port = 3000   # Match this to the app's listening port
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50
